version: '3'

tasks:
  dev:
    desc: Run server in dev
    deps: [dev-server, dev-ui]

  dev-ui:
    desc: Run frontend in dev
    cmds:
      - pnpm dev

  dev-server:
    desc: Build frontend and backend in development mode
    deps: [docs]
    cmds:
      - swag init -g cmd/server/main.go -o docs
      - go run ./cmd/server -enable-docs

  test:
    cmds:
      - go test ./...

  docs:
    desc: Generate Swagger documentation
    cmds:
      - swag init -g cmd/server/main.go -o docs

  build:
    desc: Build frontend and backend
    deps: [docs, build-ui]
    cmds:
      - go build -o dist/mediago-player.exe ./cmd/server

  build-ui:
    desc: Build frontend app only
    cmds:
      - cd ui && pnpm build
      - rm -rf assets/ui
      - cp -r ui/dist/. assets/ui

  run:
    cmds:
      - ./dist/server
