version: '3'

tasks:
  dev:
    desc: Run server in dev
    cmds:
      # Generate Swagger docs
      - swag init -g cmd/server/main.go -o docs
      - go run ./cmd/server

  dev-server:
    desc: Build frontend and backend
    cmds:
      # Generate Swagger docs
      - swag init -g cmd/server/main.go -o docs
      # Build frontend apps
      - pnpm build
      # Copy dist folders to assets
      - rm -rf assets/desktop assets/mobile
      - mkdir -p assets/desktop assets/mobile
      - cp -r apps/web-desktop/dist/. assets/desktop/
      - cp -r apps/web-mobile/dist/. assets/mobile/
      - go run ./cmd/server

  test:
    cmds:
      - go test ./...

  swagger:
    desc: Generate Swagger documentation
    cmds:
      - swag init -g cmd/server/main.go -o docs

  build:
    desc: Build frontend and backend
    cmds:
      # Generate Swagger docs
      - swag init -g cmd/server/main.go -o docs
      # Build frontend apps
      - pnpm build
      - rm -rf assets/desktop assets/mobile
      - mkdir -p assets/desktop assets/mobile
      - cp -r apps/web-desktop/dist/. assets/desktop/
      - cp -r apps/web-mobile/dist/. assets/mobile/
      # Build Go binary
      - go build -o dist/server.exe ./cmd/server

  run:
    cmds:
      - ./dist/server
